### ISSUE TITLE
Cannot find proj_api.h header

### ISSUE THREAD

**Issue by wonderer007** [cfis/proj4rb#10]
```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/AqsaArshad/.rvm/gems/ruby-2.3.8/gems/proj4rb-1.0.0/ext
/Users/AqsaArshad/.rvm/rubies/ruby-2.3.8/bin/ruby -r ./siteconf20190519-39743-1y1c1ad.rb extconf.rb
checking for proj_api.h... no
extconf.rb:6:in `<main>': Cannot find proj_api.h header (RuntimeError)

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/AqsaArshad/.rvm/gems/ruby-2.3.8/extensions/x86_64-darwin-18/2.3.0/proj4rb-1.0.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/AqsaArshad/.rvm/gems/ruby-2.3.8/gems/proj4rb-1.0.0 for inspection.
Results logged to /Users/AqsaArshad/.rvm/gems/ruby-2.3.8/extensions/x86_64-darwin-18/2.3.0/proj4rb-1.0.0/gem_make.out

An error occurred while installing proj4rb (1.0.0), and Bundler cannot continue.
Make sure that `gem install proj4rb -v '1.0.0' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  global_convert was resolved to 0.0.2, which depends on
    proj4rb
```

`ruby 2.3.8p459 (2018-10-18 revision 65136) [x86_64-darwin18]`

**Comment by michaels-terravesta** [comment]
I have the same issue

```
Building native extensions.  This could take a while...
ERROR:  Error installing proj4rb:
        ERROR: Failed to build gem native extension.

    current directory: /Users/michaels/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/proj4rb-1.0.0/ext
/Users/michaels/.rbenv/versions/2.4.0/bin/ruby -r ./siteconf20190607-47878-1wpsuvv.rb extconf.rb
checking for proj_api.h... no
extconf.rb:6:in `<main>': Cannot find proj_api.h header (RuntimeError)

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/michaels/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/extensions/x86_64-darwin-16/2.4.0-static/proj4rb-1.0.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/michaels/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/proj4rb-1.0.0 for inspection.
Results logged to /Users/michaels/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/extensions/x86_64-darwin-16/2.4.0-static/proj4rb-1.0.0/gem_make.out
```

When I look in the mkmf.log file I see the following error

```
/usr/local/include/proj_api.h:37:2: error: 'To use the proj_api.h you must define the macro ACCEPT_USE_OF_DEPRECATED_PROJ_API_H'
#error 'To use the proj_api.h you must define the macro ACCEPT_USE_OF_DEPRECATED_PROJ_API_H'

```

**Comment by martinGerez** [comment]
Hi. That's not a problem with Ruby version. Is a problem with the last release of Proj4 and Proj4rb gem.
Proj4rb needs to be updated.

Could you confirm that have Proj4 v6?
Needed downgrade Proj4 with this workaround: https://github.com/SciTools/cartopy/issues/1288#issuecomment-491100316

https://github.com/OSGeo/PROJ/releases --> Error is triggered by this point may be:
```
Deprecated the proj_api.h interface. The header file is still available
but will be removed with the next major version release of PROJ. It is
now required to define ACCEPT_USE_OF_DEPRECATED_PROJ_API_H before the
interface can be used 
```

**Comment by jklimke** [comment]
I just fixed the issue in pull request #11 

If this intermediate solution is ok, it would be nice if this could be merged.

**Comment by kurko** [comment]
@jklimke fixes it. @cfis any chance 1.0.1 could be released? That way I don't need to install it from Github :)

**Comment by cfis** [comment]
Yes, I can do that.

**Comment by cfis** [comment]
I'm going to release version 2 of the gem that is designed to work with Proj5 and Proj6, but still be backwards compatible.
